name: CI

on:
  workflow_call:
    inputs:
      go_version:
        description: 'Go version'
        required: false
        default: v1.17
        type: string
      node_version:
        description: 'Node version'
        required: false
        default: 16
        type: string
      go_lint_version:
        description: 'Go lint version'
        required: false
        default: v1.45.0
        type: string
      setup:
        description: 'Run setup makefile. If set to true, a make target named "setup" must exist'
        required: false
        default: false
        type: boolean
      gosec:
        description: 'Run Gosec Security Scanner'
        required: false
        default: true
        type: boolean
      working_directory:
        description: 'The working directory (root) for running workflow. Usually, this is ., the root directory of the app'
        required: false
        default: '["."]'
        type: string

jobs:
  # Runs continuous integration test
  test:
    runs-on: ubuntu-latest
    env:
      GO111MODULE: on
    strategy:
      matrix:
        working_dir: ${{ fromJSON(inputs.working_directory) }}
    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Presetup environment
      if: inputs.setup == true
      shell: bash
      run: |-
        make setup

    - name: Setup Go
      uses: actions/setup-go@v3
      with:
        go-version: ${{ inputs.go_version }}

    - name: Setup golangci-lint
      uses: golangci/golangci-lint-action@v3
      with:
        version: ${{ inputs.go_lint_version }}

    - name: Setup Node
      uses: actions/setup-node@v3
      with:
        node-version: ${{ inputs.node_version }}

    - name: Go Format
      run: |
        go fmt ./...

    - name: Go Test
      run: |
        go test -v ./...

    - name: Other Tests
      run: |
        make ci

    - if: inputs.gosec == true
      name: Gosec Security Scanner
      working-directory: ${{ matrix.working_dir }}
      uses: securego/gosec@master

    - name: Set up Helm
      uses: azure/setup-helm@v2.0
      with:
        version: v3.6.3

    - name: Run Lint
      run: |
        make lint

    - name: Run helm lint
      run: |
        make helm_lint
