name: CI

on:
  workflow_call:
    inputs:
      go_version:
        description: 'Go version'
        required: false
        default: 'stable'
        type: string
      node_version:
        description: 'Node version'
        required: false
        default: 16
        type: string
      go_lint_version:
        description: 'Go lint version'
        required: false
        default: latest
        type: string
      setup:
        description: 'Run setup makefile. If set to true, a make target named "setup" must exist'
        required: false
        default: false
        type: boolean
      gosec:
        description: 'Run Gosec Security Scanner'
        required: false
        default: true
        type: boolean
      vulncheck:
        description: 'Run govulncheck Scanner'
        required: false
        default: true
        type: boolean

jobs:
  # Runs continuous integration test
  test:
    runs-on: ubuntu-latest
    env:
      GO111MODULE: on
    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - if: inputs.setup == true
      uses: abbbi/github-actions-tune@v1

    - name: Presetup environment
      if: inputs.setup == true
      shell: bash
      run: |-
        make setup

    - name: Setup Go
      uses: actions/setup-go@v4
      with:
        go-version: ${{ inputs.go_version }}
        cache: true

    - name: Setup golangci-lint
      uses: golangci/golangci-lint-action@v3
      with:
        version: ${{ inputs.go_lint_version }}
        args: --timeout 3m

    - name: Setup Node
      uses: actions/setup-node@v3
      with:
        node-version: ${{ inputs.node_version }}

    - name: Go Format
      run: |
        go fmt ./...

    - name: Go Test
      run: |
        go test -v ./...

    - name: Other Tests
      run: |
        make ci

    - if: inputs.gosec == true
      name: Gosec Security Scanner
      uses: securego/gosec@master
      with:
        args: ./...

    - if: inputs.vulncheck == true
      name: Govuln Check Scanner
      uses: golang/govulncheck-action@v1
      with:
        args: ./...

    - name: Set up Helm
      uses: azure/setup-helm@v3
      with:
        version: v3.6.3

    - name: Run helm lint
      run: |
        make helm_lint
