name: CI

on:
  workflow_call:
    inputs:
      go_version:
        description: 'Go version'
        required: false
        default: v1.16
        type: string
      node_version:
        description: 'Node version'
        required: false
        default: 14
        type: string
      go_lint_version:
        description: 'Go lint version'
        required: false
        default: v1.43.0
        type: string
      setup:
        description: 'Run setup makefile. If set to true, a make target named "setup" must exist'
        required: false
        default: false
        type: boolean
      gosec:
        description: 'Run Gosec Security Scanner'
        required: false
        default: false
        type: boolean

jobs:
  # Runs continous integration test
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Code
      uses: actions/checkout@v2

    - name: Presetup environment
      if: inputs.setup == true
      shell: bash
      run: |-
        make setup

    - name: Setup Go
      uses: actions/setup-go@v2
      with:
        go-version: ${{ inputs.go_version }}

    - name: Setup golangci-lint
      uses: golangci/golangci-lint-action@v2
      with:
        version: ${{ inputs.go_lint_version }}

    - name: Setup Node
      uses: actions/setup-node@v2
      with:
        node-version: ${{ inputs.node_version }}

    - name: Go Format
      run: |
        go fmt ./...

    - name: Go Test
      run: |
        go test -v ./...

    - name: Other Tests
      run: |
        make ci

    - if: inputs.gosec == true
      name: Gosec Security Scanner
      run: |
        export PATH=$PATH:$(go env GOPATH)/bin
        go install github.com/securego/gosec/v2/cmd/gosec@v2.9.5
        gosec './...'

    - name: Set up Helm
      uses: azure/setup-helm@v1
      with:
        version: v3.6.3

    - name: Run Lint
      run: |
        make lint

    - name: Run helm lint
      run: |
        make helm_lint
