name: CI

on:
  workflow_call:
    inputs:
      gosec:
        description: 'Run Gosec Security Scanner'
        required: false
        default: true
        type: boolean
      working_directory:
        description: 'The working directory (root) for running workflow. Usually, this is ., the root directory of the app'
        required: false
        default: .
        type: string

jobs:
  scanner:
    runs-on: ubuntu-latest
    env:
      GO111MODULE: on
    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - if: inputs.gosec == true
      name: Gosec Security Scanner
      uses: securego/gosec@master
      with:
        args: ./...
