name: Tag Bump
on: 
  push:
    branches: [ main ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3.1.0

    - name: Bump version and push tag
      uses: anothrNick/github-tag-action@1.38.0
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        WITH_V: true
        RELEASE_BRANCHES: main
        PRERELEASE_SUFFIX: stage
