name: Test VERSION 2
on: 
  push:
    branches: [ dev ]

jobs:
  call-version-with-github:
    uses: TrafficDriven/ml-deployer/.github/workflows/version.yml@dev
    with:
      go_version: v1.18
      skip_ci: false
    secrets:
      token: ${{ secrets.GITHUB_TOKEN }}
