name: Test CR
on:
  push:
    branches: [ main ]

permissions:
  id-token: write
  contents: read

jobs:
  call-version:
    uses: TrafficDriven/ml-deployer/.github/workflows/version.yml@main
    secrets:
      token: ${{ secrets.PUSH_TOKEN }}

  call-cr:
    uses: TrafficDriven/ml-deployer/.github/workflows/cd.yml@main
    with:
      repository_project_id: tdt-platform
      repository: mintlist
      image: ml-deployer
      environment: ${{ github.event.inputs.environment }}
    secrets:
      slack_bot_token: ${{ secrets.SLACK_BOT_TOKEN }}
      workload_identity_provider: ${{ secrets.WORKLOAD_IDENTITY_PROVIDER }}
      service_account: ${{ secrets.GOOGLE_SERVICE_ACCOUNT }}
      slack_channel_id: ${{ secrets.TEST_SLACK_CHANNEL }}
