name: Test VERSION
on: 
  push:
    branches: [ dev ]

jobs:
  call-version:
    uses: TrafficDriven/ml-deployer/.github/workflows/version.yml@dev
    with:
      go_version: v1.17
    secrets:
      token: ${{ secrets.PUSH_TOKEN }}

  call-version-with-github:
    uses: TrafficDriven/ml-deployer/.github/workflows/version.yml@dev
    with:
      go_version: v1.17
      skip_ci: false
    secrets:
      token: ${{ secrets.GIHUB_TOKEN }}

  call-cr-if-bumped:
    if: needs.call-version.outputs.bumped
    needs: call-version
    uses: TrafficDriven/ml-deployer/.github/workflows/cd.yml@dev
    with:
      repository_project_id: tdt-platform
      repository: mintlist
      image: ml-deployer
      environment: dev
    secrets:
      slack_bot_token: ${{ secrets.SLACK_BOT_TOKEN }}
      workload_identity_provider: ${{ secrets.WORKLOAD_IDENTITY_PROVIDER }}
      service_account: ${{ secrets.GOOGLE_SERVICE_ACCOUNT }}
      slack_channel_id: ${{ secrets.TEST_SLACK_CHANNEL }}
