name: Test VERSION
on: 
  push:
    branches: [ dev ]

permissions:
  id-token: write
  contents: read

jobs:
  # This would conflict with test-version-github and may fail, but that's fine too
  call-version:
    uses: TrafficDriven/ml-deployer/.github/workflows/version.yml@dev
    secrets:
      token: ${{ secrets.PUSH_TOKEN }}

  call-cr-if-bumped:
    if: needs.call-version.outputs.bumped
    needs: call-version
    uses: TrafficDriven/ml-deployer/.github/workflows/cd.yml@dev
    with:
      repository_project_id: tdt-platform
      repository: mintlist
      image: ml-deployer
      environment: dev
    secrets:
      slack_bot_token: ${{ secrets.SLACK_BOT_TOKEN }}
      workload_identity_provider: ${{ secrets.WORKLOAD_IDENTITY_PROVIDER }}
      service_account: ${{ secrets.GOOGLE_SERVICE_ACCOUNT }}
      slack_channel_id: ${{ secrets.TEST_SLACK_CHANNEL }}
