name: Test CD
on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to deploy'
        required: false
        default: 'dev'

permissions:
  id-token: write
  contents: read

jobs:
  call-cd:
    uses: TrafficDriven/ml-deployer/.github/workflows/cd.yml@v0.0.21
    with:
      go_version: v1.17
      repository_project_id: tdt-platform
      gke_project_id: tdt-mintlist-${{ github.event.inputs.environment }}
      repository: mintlist
      image: ml-deployer
      environment: ${{ github.event.inputs.environment }}
      gke_cluster: tdt-ml-${{ github.event.inputs.environment }}
      slack_channel_id: "C02J5PUMLS1"
    secrets:
      slack_bot_token: ${{ secrets.SLACK_BOT_TOKEN }}
      workload_identity_provider: ${{ secrets.GHA_WORKLOAD_IDENTITY_PROVIDER }}
      service_account: ${{ secrets.GHA_GOOGLE_SERVICE_ACCOUNT }}
