name: Test VERSION
on: 
  push:
    branches: [ dev ]

jobs:
  call-version:
    uses: TrafficDriven/ml-deployer/.github/workflows/version.yml@dev
    with:
      go_version: v1.17
    secrets:
      token: ${{ secrets.PUSH_TOKEN }}
