name: Test CR
on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to deploy'
        required: false
        default: 'dev'

permissions:
  id-token: write
  contents: read

jobs:
  call-version:
    uses: TrafficDriven/ml-deployer/.github/workflows/version.yml@dev
    secrets:
      token: ${{ secrets.PUSH_TOKEN }}

  call-cr:
    uses: TrafficDriven/ml-deployer/.github/workflows/cd.yml@dev
    with:
      repository_project_id: tdt-platform
      repository: mintlist
      image: ml-deployer
      environment: ${{ github.event.inputs.environment }}
    secrets:
      slack_bot_token: ${{ secrets.SLACK_BOT_TOKEN }}
      workload_identity_provider: ${{ secrets.WORKLOAD_IDENTITY_PROVIDER }}
      service_account: ${{ secrets.GOOGLE_SERVICE_ACCOUNT }}
      slack_channel_id: ${{ secrets.TEST_SLACK_CHANNEL }}
