name: Test CI
on: 
  pull_request:
    branches: [ main ]

jobs:
  call-ci:
    uses: TrafficDriven/ml-deployer/.github/workflows/ci.yml@dev
    with:
      go_version: v1.20

  call-ci-with-setup:
    uses: TrafficDriven/ml-deployer/.github/workflows/ci.yml@dev
    with:
      go_version: v1.17
      setup: true
