name: VERSION

on:
  workflow_call:
    inputs:
      go_version:
        description: 'Go version'
        required: false
        default: v1.16
        type: string
      skip_ci:
        description: 'Add Skip CI to comment'
        required: false
        default: true
        type: boolean
      bump_target:
        description: 'The makefile target for bumping application version'
        required: false
        default: bump
        type: string
    outputs:
      bumped:
        description: "The version was bumped"
        value: ${{ jobs.version.outputs.bumped }}
    secrets:
      token:
        description: 'The Github Token to used for authentication'
        required: true

jobs:
  version:
    runs-on: ubuntu-latest
    outputs:
      bumped: ${{ steps.bump_version.outputs.bumped }}
    steps:
    - name: Checkout Code
      uses: actions/checkout@v3.1.0
      with:
        fetch-depth: 0
        token: ${{ secrets.token }}

    - name: Setup Go
      uses: actions/setup-go@v2
      with:
        go-version: ${{ inputs.go_version }}

    - name: Install Go Dependencies
      run: go version

    - name: Setting branch name
      run: |-
        echo "BRANCH=$(echo ${GITHUB_REF##*/})" >> $GITHUB_ENV

    - name: Setting Version Bump level to Patch
      if: contains(github.event.head_commit.message, '[bugfix]')
      run: |
        echo "BUMP=patch" >> $GITHUB_ENV
        echo "PUSH=1" >> $GITHUB_ENV

    - name: Setting Version Bump level to Minor
      if: contains(github.event.head_commit.message, '[feature]')
      run: |
        echo "BUMP=minor" >> $GITHUB_ENV
        echo "PUSH=1" >> $GITHUB_ENV

    - name: Bump Version
      if: env.PUSH == 1
      id: bump_version
      run: |
        echo "::set-output name=version::$(make ${{ inputs.bump_target }})"
        echo "::set-output name=bumped::true"

    - name: Commit Message
      if: env.PUSH == 1
      id: commit_message
      run: |
        if ${{ inputs.skip_ci }} ; then
          echo "::set-output name=message::Bump version to ${{ steps.bump_version.outputs.version }} [skip ci]"
        else
          echo "::set-output name=message::Bump version to ${{ steps.bump_version.outputs.version }}"
        fi
  
    - name: Commit files
      if: env.PUSH == 1
      run: |
        git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
        git config --local user.name "github-actions[bot]"
        git diff-index --quiet HEAD || git commit -m "${{ steps.commit_message.outputs.message }}" -a

    - name: Push changes
      if: env.PUSH == 1
      uses: nick-invision/retry@v2
      with:
        timeout_seconds: 30
        max_attempts: 5
        command: git push
        on_retry_command: |

          git config pull.rebase false
          git pull origin ${{ env.BRANCH }}
          git commit --amend -m "${{ steps.commit_message.outputs.message }}"
